version: "3.0"
services:
  api:
    stdin_open: true
    tty: true
    container_name: "hr-rocket-api"
    env_file:
      - .env
    build: .
    command: /venv/bin/uvicorn app.main:app --host=0.0.0.0 --port=80 --reload
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      pg:
        condition: service_healthy


  pg:
    container_name: pg
    volumes:
      - postgresdata:/var/lib/postgresql/data
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=hr-rocket-api
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 6s
      timeout: 2s
      retries: 5


volumes:
  postgresdata:
